version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: container
    environment:
      MYSQL_ROOT_PASSWORD: akucintastima
      MYSQL_DATABASE: applicant_db
      MYSQL_USER: kerjalembut
      MYSQL_PASSWORD: akucintastima
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

volumes:
  db_data: